# Site wide configuration

title: Montreal JUG
locale: fr_CA
description: Le Montréal JUG est une association à but non lucratif dont l’objectif est d’organiser des conférences et rencontres gratuites et accessibles dans le domaine du langage de programmation Java. Les conférences sont en français ou en anglais, à la discrétion du présentateur. Le Montréal JUG est aussi l’un des plus gros JUG au monde avec plus de 1130 membres et une audience moyenne de 65 professionnels en informatique à chaque conférence, et une croissance en 2015-2016 de 40 nouveaux membres par mois!
logo: logo.png
search: false
url: http://montreal-jug.org
#url: http://localhost:4000
version: 6
navbar: true

# Jekyll configuration
future: true
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugin:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Montreal JUG
  avatar: photo.jpg
  email: info@montreal-jug.org
  disqus-shortname: montrealjug
  twitter: montrealjug
  github: montrealjug
  linkedin:
  meetup: montreal-jug
  facebook: "pages/Montreal-Java-User-Group/145299602245793"
  stackexchange:
  instagram:
  flickr:
  tumblr:
  google:
    plus:
    analytics: UA-25715796-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
